bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 1
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 1e-3
learning_rate_te1 = 1e-5
learning_rate_te2 = 1e-5
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 2500
min_bucket_reso = 256
mixed_precision = "bf16"
multires_noise_discount = 0.3
noise_offset_type = "Original"
optimizer_type = "Adafactor"
output_dir = "/workspace/flower_dreambooth"
output_name = "last"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
reg_data_dir = "/workspace/flowers-reg-sdxl/reg"
resolution = "1024,1024"
sample_prompts = "/workspace/kohya_ss/outputs/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
train_batch_size = 1
train_data_dir = "/workspace/flowers-reg-sdxl/train"
xformers = true
no_half_vae = true
